[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
authors = ["slbsh"]
license = "0BSD"

[dependencies]

[profile.release]
lto = true
panic = "abort"
opt-level = "z"
debug = false
strip = true
codegen-units = 1
